### ISSUE TITLE
compiler error for BOUT++-v4.2.2

### ISSUE THREAD

**Issue by wphu** [boutproject/hermes#4]
Many compiler error:

hermes-1.cxx:298:21: error: ‘class Mesh’ has no member named ‘g11’
     g11norm = mesh->g11 / averageY(mesh->g11);
                     ^~~
hermes-1.cxx:298:42: error: ‘class Mesh’ has no member named ‘g11’
     g11norm = mesh->g11 / averageY(mesh->g11);
                                          ^~~
hermes-1.cxx:383:33: error: ‘class Mesh’ has no member named ‘ngx’
       for (int i = 0; i < mesh->ngx; i++) {
                                 ^~~
hermes-1.cxx:384:35: error: ‘class Mesh’ has no member named ‘ngy’
         for (int j = 0; j < mesh->ngy; j++) {
                                   ^~~
hermes-1.cxx:398:15: error: ‘class Solver’ has no member named ‘addToRestart’; did you mean ‘addMonitor’?
       solver->addToRestart(density_error_integral, "density_error_integral");
               ^~~~~~~~~~~~
               addMonitor
hermes-1.cxx:401:15: error: ‘class Solver’ has no member named ‘addToRestart’; did you mean ‘addMonitor’?
       solver->addToRestart(pe_error_integral, "pe_error_integral");
               ^~~~~~~~~~~~
               addMonitor
hermes-1.cxx:436:11: error: ‘class Mesh’ has no member named ‘dx’
     mesh->dx /= rho_s0 * rho_s0 * Bnorm;
           ^~
hermes-1.cxx:437:11: error: ‘class Mesh’ has no member named ‘Bxy’

**Comment by bendudson** [comment]
Currently Hermes-1 only works with BOUT++ version 3.1. Since there have been many improvements to BOUT++ since then, and a number of bugs fixed, I recommend you use Hermes-2 https://github.com/bendudson/hermes-2  which is a hot ion version.

**Comment by wphu** [comment]
> Currently Hermes-1 only works with BOUT++ version 3.1. Since there have been many improvements to BOUT++ since then, and a number of bugs fixed, I recommend you use Hermes-2 https://github.com/bendudson/hermes-2 which is a hot ion version.

OK，thank you.
I also have some problems with hermes-2 when running the example case under hermes-2.
Please reply: https://github.com/bendudson/hermes-2/issues
