### ISSUE TITLE
Error when running make

### ISSUE THREAD

**Issue by seob1** [boutproject/hermes#5]
Hi,

I am trying to run the Hermes and did 'run'. However, I've got a error as below. I would appreciate if you provide me a solution.

Thanks!

$ make
  Compiling  hermes-1.cxx
In file included from hermes-1.cxx:22:0:
hermes-1.hxx:30:10: fatal error: bout/invert/laplace3d.hxx: No such file or directory
 #include <bout/invert/laplace3d.hxx>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
../../make.config:318: recipe for target 'hermes-1.o' failed
make: *** [hermes-1.o] Error 1

**Comment by bshanahan** [comment]
Hi there,  

Yes, laplace3d has been removed from the main BOUT++ repo, so you can just comment this line out in the header file, then try again.  

I don't think this option is necessary for hermes, but @bendudson should confirm.

**Comment by bendudson** [comment]
I will have to check, but last time I tried this version of Hermes only works with BOUT++ v3.1. That can be downloaded from here: https://github.com/boutproject/BOUT-dev/releases/tag/v3.1
There is a more up-to-date version of Hermes, which includes hot ions and compiles with the latest BOUT++, available here: https://github.com/bendudson/hermes-2

**Comment by seob1** [comment]
@bshanahan and @bendudson 
Thanks you all so much!

**Comment by seob1** [comment]
@bshanahan 
I commented the line and tried to do 'make' but I've got error (this is a part of the error the error is too long to paste here):

$ make
  Compiling  hermes-1.cxx
In file included from hermes-1.hxx:31:0,
                 from hermes-1.cxx:22:
../../include/bout/invert/laplacexy.hxx:39:2: warning: #warning LaplaceXY requires PETSc. No LaplaceXY available [-Wcpp]
 #warning LaplaceXY requires PETSc. No LaplaceXY available
  ^~~~~~~
In file included from hermes-1.hxx:35:0,
                 from hermes-1.cxx:22:
radiation.hxx:22:29: error: ‘string’ does not name a type; did you mean ‘stdin’?
   InterpRadiatedPower(const string &file);
                             ^~~~~~
                             stdin
In file included from hermes-1.cxx:22:0:
hermes-1.hxx:302:3: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   const BoutReal bcast_lasty(const BoutReal f);
   ^~~~~
hermes-1.cxx: In function ‘const Field3D ceil(const Field3D&, BoutReal)’:
hermes-1.cxx:47:26: error: ‘class Mesh’ has no member named ‘ngx’
   for (int jx=0;jx<mesh->ngx;jx++)
                          ^~~
hermes-1.cxx:48:28: error: ‘class Mesh’ has no member named ‘ngy’
     for (int jy=0;jy<mesh->ngy;jy++)
                            ^~~
hermes-1.cxx:49:30: error: ‘class Mesh’ has no member named ‘ngz’
       for (int jz=0;jz<mesh->ngz;jz++) {
                              ^~~
hermes-1.cxx: In member function ‘virtual int Hermes::init(bool)’:
hermes-1.cxx:163:56: error: cannot convert ‘FieldGeneratorPtr {aka std::shared_ptr<FieldGenerator>}’ to ‘FieldGenerator*’ in assignment
     sol_ne = FieldFactory::get()->parse("sol_ne", optsc);
                                                        ^

**Comment by bshanahan** [comment]
Hi, can you please post the output of `git branch -v', both in the BOUT++ directory, and in the hermes directory?

**Comment by bendudson** [comment]
I suspect these are some of the many things which have changed in BOUT++ since this version of Hermes was last used. It does compile with BOUT++ 3.1 (2017), but many things changed in BOUT++ between v3.1 and v4.x

**Comment by seob1** [comment]
Hi @bshanahan 
Here is the output.

~/BOUT-dev/examples/hermes-master$ git branch -v
  master 3541f7bc5 Merge pull request #1869 from boutproject/mpark-lock
* next   229253f15 Merge pull request #1738 from boutproject/better-cleaning

**Comment by bshanahan** [comment]
Hi, 

Please see the comment from @bendudson.  At the moment, hermes-1 is meant to compile with BOUT++ version 3.1.  You are using a much more recent version of BOUT++.  Either switch to hermes-2, the hot ion version, or check out BOUT++ v3.1, per @bendudson:

> I will have to check, but last time I tried this version of Hermes only works with BOUT++ v3.1. That can be downloaded from here: https://github.com/boutproject/BOUT-dev/releases/tag/v3.1
> There is a more up-to-date version of Hermes, which includes hot ions and compiles with the latest BOUT++, available here: https://github.com/bendudson/hermes-2
